name: UUP and Upload to Artifact

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  uup-and-upload:
    runs-on: windows-2025

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run convert-uup
        shell: cmd
        run: uup_download_windows.cmd

      - name: Upload install.esd as artifact
        uses: actions/upload-artifact@v3
        with:
         name: install.esd
         path:./install.esd
         --no-archive: true
